version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: notif_user
      POSTGRES_PASSWORD: notif_pass
      POSTGRES_DB: notification_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notif_network

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - notif_network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq_broker
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./scripts/init-rabbitmq.sh:/docker-entrypoint-init.d/10-init.sh
    networks:
      - notif_network

  api_gateway:
    build:
      context: ../services/api_gateway
      dockerfile: Dockerfile
    container_name: api_gateway_service
    environment:
      PORT: 8080
      DATABASE_URL: postgres://notif_user:notif_pass@postgres_db:5432/notification_system
      REDIS_URL: redis_cache:6379
      RABBITMQ_URL: amqp://admin:admin123@rabbitmq_broker:5672/
      USER_SERVICE_URL: http://user_service:9000
      TEMPLATE_SERVICE_URL: http://template_service:9100
      USER_PREF_CACHE_TTL: 5m
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - notif_network

  push_service:
    build:
      context: ../services/push_service
      dockerfile: Dockerfile
    container_name: push_service
    environment:
      HTTP_PORT: 8081
      DATABASE_URL: postgres://notif_user:notif_pass@postgres_db:5432/notification_system
      REDIS_URL: redis_cache:6379
      RABBITMQ_URL: amqp://admin:admin123@rabbitmq_broker:5672/
      TEMPLATE_SERVICE_URL: http://template_service:9100
      STATUS_TABLE: notification_statuses
      FCM_SERVER_KEY: ${FCM_SERVER_KEY:-demo-key}
      FCM_ENDPOINT: https://fcm.googleapis.com/fcm/send
      PROVIDER_TIMEOUT: 10s
      RETRY_MAX_ATTEMPTS: 4
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - notif_network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  notif_network:
    driver: bridge
